### PR TITLE
Working improved version inspired by Canva editor

### PR DESCRIPTION
**Pull request by LG33**
Hi,

I fixed the bugs and improved a lot the UX. I was inspired by the Canva editor.
I hope this PR will be accepted and published on pub.dev soon because I need this package in a FlutterFlow project.

Bug fixes:
- the scale operation is now working with any angle
- the rotation operation starts from the current angle
- JSON saving/loading is working correctly

Improvements:
- the scale operation keeps the current aspect ratio
- in order to change the aspect ratio, I added handles on the edges (for image items, the fit is set to cover by default so they can be cropped)
- when the item is too small, some handles are hidden and a drag handle appears underneath
- when an item is updated (any operation), it is moved on top of all other items
- the edit button is replaced by a double tap
- the delete button is visible only when status is editing
- more CaseStyle parameters for the frame
- in the example, I added a generate button that generate items from the clipboard string

Thank you Flutter Candies for all your open source contributions!

### CODE REVIEW

**Comment by thomasllds** [comment]
Incredible to come across this branch. Very impressive improvement work, and it interests me greatly. The pull request should be accepted and pushed to pub.dev. Or have you already pushed it via an intermediary method? In any case, excellent work, really!

**Review by thomasllds — APPROVED** [review]

**Comment by LG33** [comment]
thank you @thomasllds!
no i didn't published the changes anywhere, i worked on other stuffs since then.
i hope we'll get a response because otherwise i will have to create another package in order to publish them.
the main feature that i'd like to add next is image cropping

**Comment by thomasllds** [comment]
Thank you, I see that your goal was to include this in FlutterFlow. I have also done that with version 0.1.2. However, I would really like to see your new features in a new release of this package. I don't know how to contact FlutterCandies to get them to update this package with these modifications on Pub.dev. Otherwise, how can I support you so that you can publish this package yourself quickly? Thanks    And for the image cropping, that would be amazing ;)

**Comment by LG33** [comment]
It seems that fluttercandies are still active. They updated a package 14 days ago. You could try to send an email to [fluttercandies@googlegroups.com](mailto:fluttercandies@googlegroups.com)?
Otherwise publishing a package on pub.dev doesn't seem complicated. It's just that it would be confusing for everyone, but it can be a temporary solution.

**Comment by xSILENCEx** [comment]
0.2.0 Released

I got the email, and I apologize for the late reply, I've been busy at work lately!
Thank you for your contribution!

**Comment by thomasllds** [comment]
@xSILENCEx
 It's not a problem regarding the delay, and thank you very much for this update ;) 
I completely understand, work can be very demanding.
🤜🤛

**Pull request merged**
